In [78]:
import numpy as np
import random
rng = np.random.default_rng()

In [79]:
def stringgenerator(movelength):
    stringlist = ''
    for i in range(int(movelength/2)):
        stringlist += '0'
    for j in range(int(movelength/2)):
        stringlist += '1'

    shuffled = ''.join(random.sample(stringlist,len(stringlist)))
    
    return shuffled

def outof_bounds(y,x,size):
    bool1 = False
    if y > size or x > size:
        bool1 = True
    
    return bool1



In [80]:
list_of_valid_paths = []

state = False
size = 20
movement_grid = size +1
movelength = 2*size

while state == False:
    seed = stringgenerator(movelength)
    print(trial)

    board = np.zeros((movement_grid,movement_grid))
    board[board == 0] = int(0)      
    board[0][0] = 1
    y,x = 0,0
    print(board)
    
    for char in range(len(trial)):
        step = trial[char]
        print(step)
        if step == '0':
            board[y][x] = 0
            new_y = y + 1
            board[new_y][x] = 1
            y = new_y


        else:
            board[y][x] = 0
            new_x = x + 1
            board[y][new_x] = 1
            x = new_x

            
        
        print(board)
        if board[movement_grid-1][movement_grid-1] == 1:
            state = True
            

        char += 1

0110111101010000100010011011111000110010
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [84]:
def main():
    grid = 20
    numbers = []

    for i in range(grid+1):
        numbers.append(1)
        
    for k in range(grid):
        for i in range(1, grid+1):
            numbers[i] = numbers[i] + numbers[i-1]
            
    print(numbers[-1])

main()

137846528820


In [89]:
size = 2

def recursion(right,down):
    if right == down:
        return 2 * recursion(right+1, down)
    if right >= size or down >= size:
        return 1
    count = recursion(right+1, down)
    return count + recursion(right, down+1)

print(recursion(2,0))


1


In [ ]:
0,0
2*3
6
size = 2
def rec(right, down):
    if right>= size or down >= size:
        stop going right/down
    return 

lumagpas sa grid

In [91]:
def fib(n):
    if n > 2:
        return fib(n-2) + fib(n-1)
    elif n == 2:
        return 1
    else:
        return 0

fib(5)

0,1,1,2,3

3

import org.apache.commons.lang3.time.StopWatch;
import org.junit.jupiter.api.Test;

public class Problem15 {
    private static final int SIZE = 20;

    @Test
    public void run() {
        StopWatch watch = new StopWatch();
        watch.start();
        long solution = solve();
        watch.stop();
        System.out.printf("solution: %d took %,.6f ms\n", solution,
        ((double)watch.getNanoTime()) / 1_000_000.0);
    }

    private long solve() {
        return findAllPaths(0, 0);
    }

    private long findAllPaths(int rightCount, int downCount) {
        if (rightCount == downCount) {
            // symmetry => as many paths starting to go right as to go down
            return 2 * findAllPaths(rightCount + 1, downCount );
        }
        if (rightCount >= SIZE || downCount >= SIZE) return 1;
        long count = findAllPaths(rightCount + 1, downCount );
        return count + findAllPaths(rightCount, downCount + 1);
    }
}